---
php_ppa: "ppa:ondrej/php"
php_packages:
  - php7.1-common
  - php7.1-cli
  - php7.1-intl
  - php7.1-curl
  - php7.1-cgi
  - php7.1-fpm
  - php7.1-mysql
  - php7.1-gd
  - php7.1-mcrypt
  - php7.1-mbstring
php_timezone: America/Los_Angeles
php_upload_max_filesize: "20M"
php_post_max_size: "20M"
php_memory_limit: "1024M"
php_max_execution_time: 60

php_opcache_enable: 1
php_opcache_revalidate_freq: 2592000
php_opcache_opcache_validate_timestamps: 1
php_opcache_max_accelerated_files: 20000
php_opcache_memory_consumption: 192
php_opcache_interned_strings_buffer: 16
php_opcache_fast_shutdown: 1

php_allow_url_fopen: 0

composer_path: /usr/local/bin/composer
composer_update: true
composer_update_day: 20
composer_path_env: False
#composer_home_path: /opt/composer
composer_home_owner: root
composer_home_group: root
composer_global_packages: {}

# Visit https://github.com/settings/applications
# and generate personal access token
composer_github_oauth: false
composer_http_basic: false